name: 'Bug report (Browser)'
description: I experience unexpected behavior using the library in a browser.
labels: ['bug', 'scope:browser', 'needs:triage']
body:
  - type: markdown
    attributes:
      value: Thank you for reporting an issue to Mock Service Worker! Please fill in the template below to help our team tackle it in the most efficient way.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Before we begin, let's make sure your issue hasn't been solved already.
      options:
        - label: I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
          required: true
        - label: I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue
          required: true

  - type: checkboxes
    attributes:
      label: Environment check
      options:
        - label: I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
          required: true
        - label: I'm using Node.js version 18 or higher
          required: true

  - type: dropdown
    attributes:
      label: Browsers
      description: Select in which browser(s) you're experiencing the issue.
      multiple: true
      options:
        - 'Chromium (Chrome, Brave, etc.)'
        - 'Firefox'
        - 'Safari'

  - type: input
    attributes:
      label: Reproduction repository
      description: A link to the repository where your issue can be reproduced. You can clone one of [our examples](https://github.com/mswjs/examples) to create a reproduction repository much faster. **Issues without a reproduction repository will be closed**.
      placeholder: i.e. https://github.com/you/msw-issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction steps
      description: Include any steps necessary to reproduce the issue in the repository above.
      placeholder: i.e. "npm test"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current behavior
      description: Share any details on what behavior you're experiencing (error messages, logs, context).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What do you expect to happen instead?
    validations:
      required: true
