name: release-preview

on:
  push:
    branches-ignore:
      - 'main'
    tags:
      - '!**'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093
        with:
          version: 9.15.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium --with-deps --only-shell

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Tests
        run: pnpm test

      - name: Publish preview
        run: pnpm dlx pkg-pr-new@0.0 publish --compact --pnpm --comment=update
