name: smoke

on:
  workflow_run:
    workflows: ['ci']
    branches: [main]
    types: [completed]

jobs:
  test-smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Smoke tests
        run: yarn test:smoke
