name: ci

on:
  workflow_run:
    workflows: ['ci']
    branches: [main]
    types: [completed]

jobs:
  test-smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Smoke tests
        run: yarn test:smoke
