name: smoke

on:
  workflow_run:
    workflows: ['ci']
    branches: [main]
    types: [completed]

jobs:
  test-smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        with:
          version: 7.12

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Smoke tests
        run: pnpm test:smoke
